# Generated by Django 6.0.2 on 2026-02-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pagina_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created_when',
            new_name='creation_date',
        ),
    ]
