# Generated by Django 6.0.2 on 2026-03-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_user_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
