# Generated by Django 6.0.2 on 2026-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupfile'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='personal_tasks', to='groups.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
