# Generated by Django 6.0.2 on 2026-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_before_task',
            field=models.BooleanField(default=False),
        ),
    ]
