# Generated by Django 6.0.2 on 2026-05-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_board'),
        ('tasks', '0003_subtask_completed_before_task'),
    ]

    operations = [
    ]
