# Generated by Django 6.0.2 on 2026-05-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description_subtask_completed_before_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='image',
        ),
        migrations.AddField(
            model_name='taskimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
