# Generated by Django 6.0.2 on 2026-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
