# Generated by Django 6.0.2 on 2026-05-16 16:08

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.user_file_path),
        ),
    ]
