# Generated by Django 6.0.2 on 2026-05-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_image_url'),
        ('files', '0002_file_nickname_generic_fk'),
    ]

    operations = [
    ]
