# Generated by Django 6.0.2 on 2026-05-22 22:52

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_merge_20260518_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.user_file_path),
        ),
    ]
