# Generated by Django 6.0.2 on 2026-05-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_merge_20260518_0246'),
        ('files', '0004_alter_file_file'),
    ]

    operations = [
    ]
