# Generated by Django 6.0.2 on 2026-02-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='criada_em',
            new_name='created_when',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='titulo',
            new_name='title',
        ),
    ]
